# .circleci/config.yml
version: 2.1

executors:
  macos-xcode:
    macos:
      xcode: "16.4.0"

jobs:
  build-and-test:
    executor: macos-xcode
    steps:
      - checkout

      # 1) Restore CocoaPods cache (if you’re using Pods in Build/)
      - restore_cache:
          keys:
            - cocoapods-{{ checksum "Build/Podfile.lock" }}
            - cocoapods-

      # 2) Install Pods (only if there’s a Podfile under Build/)
      - run:
          name: Install CocoaPods
          command: |
            if [ -f Build/Podfile ]; then
              cd Build
              pod install --repo-update
            fi

      # 3) Save CocoaPods cache
      - save_cache:
          paths:
            - Build/Pods
            - ~/.cocoapods
          key: cocoapods-{{ checksum "Build/Podfile.lock" }}

      # 4) Build & test on the Simulator
      - run:
          name: Build & Test on iOS Simulator
          command: |
            set -o pipefail
            cd Build
            if [ -d Unity-iPhone.xcworkspace ]; then
              xcodebuild \
                -workspace Unity-iPhone.xcworkspace \
                -scheme Unity-iPhone \
                -configuration Release \
                -sdk iphonesimulator \
                -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" \
                test | tee xcode_test.log
            else
              xcodebuild \
                -project Unity-iPhone.xcodeproj \
                -scheme Unity-iPhone \
                -configuration Release \
                -sdk iphonesimulator \
                -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" \
                test | tee xcode_test.log
            fi

      # 5) Persist logs & build output
      - store_artifacts:
          path: Build/xcode_test.log
          destination: logs
      - store_artifacts:
          path: Build/Build/Products/Release-iphonesimulator
          destination: app
      - store_test_results:
          path: Build/Build/Products/Release-iphonesimulator

workflows:
  build-and-test:
    jobs:
      - build-and-test