version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 16.4.0
    steps:
      - checkout
      - run:
          name: Build and Test
          command: xcodebuild -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' test
      - store_artifacts:
          path: build/Release-iphonesimulator
      - store_test_results:
          path: build/Release-iphonesimulator

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test